name: Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install HTSlib (libhts)
        run: |
          sudo apt-get update
          sudo apt-get install -y libhts-dev

      - name: Setup Nim
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: 'stable'

      - name: Install dependencies and run tests
        run: nimble test -y
